name: Release Geode Mod

on:
  workflow_dispatch:

jobs:
  release:
    name: Release mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hiimjasmine00/release-geode-mod@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true